config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:
      { omniauth_callbacks: 'users/omniauth_callbacks',
        registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  root 'home#index'
  get 'home/index'

  get 'users/show', as: 'user_root'
  resources :books, only: [:show]
  resources :categories, only: [:show, :index]
  resources :authors, only: [:show]
  resources :orders_items, only: [:create, :update, :destroy]
  resources :reviews, only: [:create]
  resources :orders, only: [:index, :show]
  resource :checkout, only: [:show, :update]
  resource  :cart, only: [:show]

  patch 'checkouts/make_order', as: 'make_order'
  patch 'coupons/apply', as: 'coupons'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_order
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def in_cart(book)
    current_order.orders_items.map(&:book).include? book
  end

  def order_item
    OrdersItem.new
  end

  def tab_header(name, title, enable = true, active = false)
    result = <<HTML
<li role="presentation" class="#{active ? 'active' : ''}#{enable ? '' : 'disabled'}">
  #{tab_href(title, name)}
</li>
HTML
    result.html_safe
  end

  def tab_href(content, name)
    result = <<HTML
    <a href="##{name}" aria-controls="#{name}" role="tab" data-toggle='tab' >#{content}</a>
HTML
    result.html_safe
  end
end

app/views/carts/_add_btn.html.haml
-if in_cart book
  =link_to t('.text'), cart_path, class: 'btn btn-primary to-cart'
-else
  = form_for order_item, remote: true, format: :json, html: {class:'add-to-cart form form-inline'} do |f|
    .input-group
      =f.number_field :count, value:1, min:1, max:20, class:'form-control'
      .input-group-btn
        =f.hidden_field :book_id, value: book.id
        =f.button tag('span', class:'glyphicon glyphicon-shopping-cart'), class: 'btn btn-primary'

app/views/carts/_cart_content.html.haml
.container.cart-content.text-center
  -if @order.orders_items.empty?
    %h2= t '.empty'
  -else
    %table.table.books.text-left
      %thead
        %tr
          %th
          %th= t '.book'
          %th= t '.price'
          %th= t '.quantity'
          %th= t '.total'
          %th
      %tbody
        -@order.orders_items.each do |item|
          =render 'carts/cart_row', item:item
        %tr
          %td.text-right{colspan:4}
            =render 'coupons/form', coupon: @order.coupon
          %td{colspan:2}
            %b.cart-total
              $#{current_order.total}
        %tr
          %td.text-right{colspan:5}
          %td
            =link_to t('.make-order'), checkout_path, class: 'btn btn-success'

app/views/carts/_cart_row.html.haml
%tr[item]
  =form_for item, remote: true,format: :json do |f|
    %td
      =link_to item.book do
        =image_tag item.book.image.url, height: '80px', class:'img-thumbnail'
    %td
      =link_to item.book do
        =item.book.title
    %td
      $#{item.cost}
    %td.count
      =f.number_field :count, value: item.count.to_i, class: 'form-control count', min:1, max: 20
      =f.hidden_field :book_id, value: item.book.id
    %td.total
      $#{item.total}
    %td
      =f.button icon('refresh'), class: 'btn btn-primary'
      =link_to icon('remove'),
               item,
               { data: { confirm: t('.confirm', book: item.book.title), type: :json },
                         method: :delete,
                         remote: true,
                         class: "btn btn-danger" }

app/views/carts/_checkout_address.html.haml
=form_for @order,remote:true, html: {method: :put, class:'form addresses'} do |f|
  =f.hidden_field 'next_step', value: :delivery
  .row
    .col-md-6
      %h3= t('.billing')
      .billing-address
        =render 'addresses/form', address: :billing_address, form: f
    .col-md-6
      %h3= t('.shipping')
      =f.check_box :use_billing_address
      =f.label :use_billing_address, t('.use-btn')
      .shipping-address
        =render 'addresses/form', address: :shipping_address, form: f
  =render 'checkout_continue_btn', f:f

app/views/carts/_checkout_cart_row.html.haml
%tr
  %td
    =image_tag item.book.image, width: '50px'
  %td
    =item.book.title
    x
    =item.count
  %td
    $#{item.total}

app/views/carts/_checkout_confirm.html.haml
.confirm
  .row
    %h2= complited ? t('.title.complited') : t('.title.confirm')
  .row
    .col-md-3
      %h3= t('carts.checkout_address.shipping')
      -unless complited
        =button_tag(icon('edit'),class:'btn btn-link tab-link',id:'address')
      .info
        -if @order.use_billing_address
          =t('.ship_to_billing')
        -else
          =print_address(@order.shipping_address.decorate)
    .col-md-3
      %h3= t('carts.checkout_address.billing')
      -unless complited
        =button_tag(icon('edit'),class:'btn btn-link tab-link', id:'address')
      .info
        =print_address(@order.billing_address.decorate)
    .col-md-3
      %h3= t('carts.checkout.tab-delivery')
      -unless complited
        =button_tag(icon('edit'),class:'btn btn-link tab-link', id:'delivery')
      .info
        =@order.delivery.name
    .col-md-3
      %h3= t('carts.checkout.tab-payment')
      -unless complited
        =button_tag(icon('edit'),class:'btn btn-link tab-link', id:'payment')
      .info
        =print_credit_card(@order.credit_card)
  .row
    .col-md-4.col-md-push-4
      -if complited
        =link_to t('.btn_text.complited'), root_path, class:'btn btn-block btn-success'
      -else
        =form_tag make_order_url, remote: true, method: :patch, class:'form' do
          =submit_tag t('.btn_text.comfirm'), class:'btn btn-success btn-block'

app/views/carts/_checkout_continue_btn.html.haml
.row
  .col-md-4.col-md-push-4
    =f.submit t('.text'), class:'btn btn-block btn-success'

app/views/carts/_checkout_delivery.html.haml
=form_for @order,remote:true, html: {method: :put, class:'form addresses'} do |f|
  =f.hidden_field 'next_step', value: :payment
  .row
    .col-md-10.col-md-push-1
      -@deliveries.each do |delivery|
        .form-group
          =f.radio_button :delivery_id, delivery.id
          =f.label "delivery_id_#{delivery.id}", "#{delivery.name} - $#{delivery.cost}"
  =render 'checkout_continue_btn', f:f

app/views/carts/_checkout_summary.html.haml
%table.table.table-striped.table-bordered.text-center
  -order.orders_items.each do |item|
    =render 'carts/checkout_cart_row', item: item

  -if order.coupon.present?
    %tr
      %td.text-right{colspan:2}
        %b= t '.discount'
        %td
          #{order.coupon.discount}%
  %tr
    %td.text-right{colspan:2}
      %b= t('.subtotal')
      %td
        $#{order.subtotal}
  -if order.delivery.present?
    %tr
      %td.text-right{colspan:2}
        %b= t '.delivery'
        %td
          $#{order.delivery.cost}
  %tr
    %td.text-right{colspan:2}
      %b= t '.total'
    %td
      $#{order.total}

app/views/carts/checkout.html.haml
%h1 Checkout
.col-md-8.checkout
  %ul.nav.nav-tabs{role:"tablist"}
    =tab_header 'address', t('.tab-address'), true, true
    =tab_header 'delivery', t('.tab-delivery'), false
    =tab_header 'payment', t('.tab-payment'), false
    =tab_header 'confirm', t('.tab-confirm'), false
    =tab_header 'complete', t('.tab-complete'), false
  %div.tab-content
    %div.tab-pane.fade-in.active{role:"tabpanel", id:"address"}
      = render 'carts/checkout_address'
    %div.tab-pane.fade{role:"tabpanel", id:"delivery"}
      = render 'carts/checkout_delivery'
    %div.tab-pane.fade{role:"tabpanel", id:"payment"}
      = render 'carts/checkout_payment'
    %div.tab-pane.fade{role:"tabpanel", id:"confirm"}

    %div.tab-pane.fade{role:"tabpanel", id:"complete"}

.col-md-4
  %h3.text-center= t('.summary')
  .order-summary
    =render 'checkout_summary', order: @order

app/views/carts/show.html.haml
%h1= t '.title'

=render 'carts/cart_content'