config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:
      { omniauth_callbacks: 'users/omniauth_callbacks',
        registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  root 'home#index'
  get 'home/index'

  get 'users/show', as: 'user_root'
  resources :books, only: [:show]
  resources :categories, only: [:show, :index]
  resources :authors, only: [:show]
  resources :orders_items, only: [:create, :update, :destroy]
  resources :reviews, only: [:create]
  resources :orders, only: [:index, :show]
  resource :checkout, only: [:show, :update]
  resource  :cart, only: [:show]

  patch 'checkouts/make_order', as: 'make_order'
  patch 'coupons/apply', as: 'coupons'
end

app/views/layouts/_body.html.haml
.container
  =render('shared/notice', message: notice) if notice.present?
  =render('shared/alert', message: flash[:alert]) if flash[:alert].present?
  -unless breadcrumbs.empty?
    %ol.breadcrumb
      =render_breadcrumbs :tag => :li, :separator => ""
  = yield

app/views/layouts/_cart_text.html.haml
=link_to "#{t(:'menu.cart')}(#{current_order.orders_items.count})", cart_path

app/views/layouts/_header.html.haml
.container
  %nav.navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{type:'button', data: {toggle:'collapse', target: '#navbar'}, aria:{expanded:'false', controls: 'navbar'}}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href:'/'}
          = image_tag '/images/logo.png', height: '40px'
      .navbar-collapse.collapse#navbar
        %ul.nav.navbar-nav
          %li
            =link_to t('menu.home'), root_path
          %li
            =link_to t('menu.shop'), categories_path
        %ul.nav.navbar-nav.navbar-right
          %li.cart-link
            =render 'layouts/cart_text'
          -if user_signed_in?
            %li
              =link_to t('menu.orders'), orders_path
            %li
              =link_to t('menu.profile'), user_root_path
            %li
              =link_to t('menu.logout'), destroy_user_session_path, method: :delete
          -else
            %li
              =link_to t('menu.signin'), new_user_session_path
            %li
              =link_to t('menu.signup'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t(:title)
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = favicon_link_tag 'favicon.ico'
  %body
    =render 'layouts/header'
    =render 'layouts/body'